spring.application.name=BootMS15-ApiGataway


server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

spring.cloud.gateway.server.webmvc.routes[0].id=employee-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://BootMS15-EmployeeService
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/employee/**


spring.cloud.gateway.server.webmvc.routes[1].id=department-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://BootMS15-DepartmentService
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/department/**